networks:
  loki:
    driver: bridge

services:
  loki:
    image: grafana/loki:3.0.0
    ports:
      - "3100:3100"
    volumes:
      - ./loki-config.yml:/etc/loki/local-config.yaml
      - loki-data:/loki
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - loki
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:3100/ready || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped

  alloy:
    image: grafana/alloy:latest
    ports:
      - "12345:12345"  # Alloy UI
    volumes:
      - ./alloy-config.alloy:/etc/alloy/config.alloy:ro
      - ./logs:/var/log/simple-proxy:ro  # Mount simple-proxy logs from observability directory
      - alloy-data:/var/lib/alloy/data
    command: 
      - run
      - /etc/alloy/config.alloy
      - --server.http.listen-addr=0.0.0.0:12345
      - --storage.path=/var/lib/alloy/data
    networks:
      - loki
    depends_on:
      loki:
        condition: service_healthy
    restart: unless-stopped

  grafana:
    image: grafana/grafana-oss:10.4.0
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_INSTALL_PLUGINS=grafana-piechart-panel
    networks:
      - loki
    depends_on:
      loki:
        condition: service_healthy
    restart: unless-stopped

volumes:
  loki-data:
  alloy-data:
  grafana-storage: